###########################################
#  Archivo: packages.R                    #
#  Autor: Enrique Holgado de Frutos       #
#  Fecha: 12/05/2023                      #
#  Descripción: Script de carga de        #
#  paquetes necesarios para las           #
#  ejecuciones.                           #
###########################################

# Confirmamos que las librerías necesarias están cargadas y de no ser así las instalamos
if(!require(tidyverse)) 
  install.packages(tidyverse, repos = "http://cran.us.r-project.org")
if(!require(flextable)) 
  install.packages(flextable, repos = "http://cran.us.r-project.org")
if(!require("odbc")) 
  install.packages("odbc", repos = "http://cran.us.r-project.org")
if(!require("DBI")) 
  install.packages("DBI", repos = "http://cran.us.r-project.org")
if(!require("ggplot2")) 
  install.packages("ggplot2", repos = "http://cran.us.r-project.org")
if(!require(plotly)) 
  install.packages(plotly, repos = "http://cran.us.r-project.org")
if(!require("git2r")) 
  install.packages("git2r", repos = "http://cran.us.r-project.org")
if(!require("here")) 
  install.packages("here", repos = "http://cran.us.r-project.org")
if(!require(DT)) 
  install.packages(DT, repos = "http://cran.us.r-project.org")
if(!require("gt")) 
  install.packages("gt", repos = "http://cran.us.r-project.org")
if(!require(kableExtra)) 
  install.packages(kableExtra, repos = "http://cran.us.r-project.org")
if(!require("formattable"))
  install.packages("formattable", repos = "http://cran.us.r-project.org")
if(!require("rgdal"))
  install.packages("rgdal", repos = "http://cran.us.r-project.org")
if(!require("sf"))
  install.packages("sf")
if(!require(leaflet))
  install.packages(leaflet, repos = "http://cran.us.r-project.org")
if(!require("ggmap")) 
  install.packages("ggmap", repos = "http://cran.us.r-project.org")
if(!require(RColorBrewer)) 
  install.packages(RColorBrewer, repos = "http://cran.us.r-project.org")
if(!require(rgdal)) 
  install.packages("rgdal")
if(!require(jpeg)) 
  install.packages(jpeg, repos = "http://cran.us.r-project.org")
if(!require(htmltools)) 
  install.packages(htmltools, repos = "http://cran.us.r-project.org")
if(!require("DataExplorer")) 
  install.packages("DataExplorer", repos = "http://cran.us.r-project.org")
if(!require("SmartEDA")) 
  install.packages("SmartEDA")
if(!require("strvalidator")) 
  install.packages("strvalidator", repos = "http://cran.us.r-project.org")
if(!require("htmlwidgets")) 
  install.packages("htmlwidgets", repos = "http://cran.us.r-project.org")
if(!require("leaflet.extras")) 
  install.packages("leaflet.extras", repos = "http://cran.us.r-project.org")
if(!require(gridExtra)) 
  install.packages(gridExtra, repos = "http://cran.us.r-project.org")
if(!require(codetools)) 
  install.packages(codetools, repos = "http://cran.us.r-project.org")
if(!require(shiny)) 
  install.packages(shiny, repos = "http://cran.us.r-project.org")

# Cargamos las librerías
library(codetools)
library(crosstalk)
library("DBI")
library(dplyr)
library(DT)
library(flextable)
library("formattable")
library(ggmap)
library("ggplot2")
library(ggplot2)
library("git2r")
library(gridExtra)
library(gt)
library(here)
library(highcharter)
library(htmltools)
library(htmlwidgets)
library(httr)
library(jpeg)
library(jsonlite)
library(knitr)
library(kableExtra)
library(later)
library(leaflet)
library(leaflet.extras)
library("odbc")
library(plotly)
library(raster)
library(RColorBrewer)
library("rgdal")
library(rgdal)
library(sf)
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(stringr)
library(tidyverse)




